apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-chart-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://167.172.9.84:8081/repository/helm-repo/
    chart: api-chart
    targetRevision: 0.1.0  # Esta versión se actualizará automáticamente
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
