apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-chart-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://167.172.9.84:8081/repository/helm-repo/
    chart: api-chart
    targetRevision: 0.1.4 # Esta versi칩n se actualizar치 autom치ticamente
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true  # Habilita la autocorrecci칩n si el estado real no coincide con el deseado
    syncOptions:
      - CreateNamespace=true
